### ISSUE TITLE
crawler requirement - convert to metadata file

### ISSUE THREAD

**Issue by dubsnipe** [OPEN-NEXT/OSHI#18]
Hi,

It should be considered that some sites may have certain types of metadata in place (or incorrectly-formed manifests). The crawler should be required to make and/or correct manifests as it goes.

**Comment by moedn** [comment]
Jepp, just found out that this is actually required in the project proposal. Had this in the [crawler requirements](tmp_requirements-crawler.md) and moved it to mandatory requirements.

Thanks for emphasising this!
