### ISSUE TITLE
determine scope of the ontology

### ISSUE THREAD

**Issue by moedn** [OPEN-NEXT/OSHI#2]
- [x] extract **competency questions** for v1.0 from [Wikibase_Qs.md](Wikibase_Qs.md)
- [x] give some practical examples / use cases
- [x] create tl;dr describing the scope

following issue: derive requirements (meta)data

**Comment by thessaly** [comment]
Nice :D Probably these generic questions can guide checkbox 3:

- What is the domain that the ontology will cover?
- For what we are going to use the ontology?
-  For what types of questions the information in the ontology should provide answers?
- Who will use and maintain the ontology?

**Comment by moedn** [comment]
done from my perspective; feel free to reopen this issue if things are unclear
