### ISSUE TITLE
repo name

### ISSUE THREAD

**Issue by moedn** [OPEN-NEXT/OSHI#21]
"The Open Source Hardware Internet" is certainly a little too much :)

It was a first idea when this repo was opened and we quickly needed a name.

However, as this is gaining more momentum and attention, I feel it's time to start the naming discussion again.

It may be important to say that this repo contains scopes of things that should have one repo each:

- metadata standard for OSH modules, building on OKHv1
- the actual wikibase instance
- crawler
- parser
- testing data (+ list of projects as source for more testing data)

Also, OHO is meant to be the frontend for this wikibase instance in the future, hence we can also rely on OHO's brand.

Suggestions are very welcome :heart:

**Comment by hoijui** [comment]
one option: make it more specific, for example:

> The P2P standard for the Open Source Hardware Internet

or

> The Communities Open Source Hardware Internet

**Comment by moedn** [comment]
How about Library of Open Source Hardware (LOSH)? :)

**Comment by hoijui** [comment]
I like! :-) !

... the only thing I do not like about it, is that a library is this huge, centralistic thing, which this project is not.

Distributed Open Source Hardware Library - DOSHL
(see also [Distributed Library](https://en.wikipedia.org/wiki/Distributed_library))
?

... but LOSH sounds nicer, and it is not too complex ... how else could we make sure it is seen as something distributed?

**Comment by hoijui** [comment]
.. evtl. einfach in der repo description das distributed/P2P erwahnen, und das reicht?

**Comment by moedn** [comment]
Yes, I guess a subtitle like
`a graph database collecting distributed standardised metadata of open source hardware`
would do it :)

**Comment by moedn** [comment]
ok, I'll rename it now since we're now addressing a wider public and LOSH is the best we have so fat :)
